DROP TABLE IF EXISTS ODONTOLOGOS;

CREATE TABLE ODONTOLOGOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NRO_MATRICULA VARCHAR(50) NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL
);

INSERT INTO ODONTOLOGOS (ID, NRO_MATRICULA, NOMBRE, APELLIDO)
VALUES (DEFAULT, 'AE700OP', 'CRISTIAN', 'CRISTALDO'),(DEFAULT, 'AE701OP', 'JESUS', 'NAVAS'),(DEFAULT, 'AE702OP', 'FEDERICO', 'VALVERDE');
